[tool.poetry]
name = "pymailsac"
version = "0.1.4"
description = "API Wrapper Client for Mailsac"
authors = ["GSejas <jsequeira03@gmail.com>"]
readme = "README.md"
classifiers = [
        'Programming Language :: Python :: 3',
        'Operating System :: OS Independent',
    ]
license = "MIT"
homepage = "https://github.com/GSejas/mailsac-pyclient"
repository = "https://github.com/GSejas/mailsac-pyclient"
documentation = "https://github.com/GSejas/mailsac-pyclient/blob/master/README.md"
keywords = ["mailsac", "api", "wrapper", "client"]

[tool.poetry.dependencies]
python = "^3.9"
pydantic = "^2.9.2"
requests = "^2.32.3"

[tool.poetry.group.dev.dependencies]
sib-api-v3-sdk = "^7.6.0"
pytest-cov = "^6.0.0"
autopep8 = "^2.3.1"
python-dotenv = "^1.0.1"
interrogate = "^1.7.0"
flake8 = "^7.1.1"
mkdocs = "^1.6.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
