[tool.poetry]
name = "veg2hab"
version = "1.0.0a1"
description = "Package voor automatisch omzetten van vegetatiekarteringen naar habitatkaarten"
authors = ["Spheer.ai <info@spheer.ai>"]
readme = "README.md"
license = "LGPLv3"
classifiers = [
  "License :: OSI Approved :: GNU Lesser General Public License v3 (LGPLv3)",

  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.7",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
]

[project.urls]
Homepage = "https://github.com/Spheer-ai/veg2hab"
Issues = "https://github.com/Spheer-ai/veg2hab/issues"
Source = "https://github.com/Spheer-ai/veg2hab"

[tool.poetry.scripts]
veg2hab = "veg2hab.__main__:veg2hab"

[tool.poetry.dependencies]
python = ">=3.7.1,<4.0"
pandas = "^1.3.0"
geopandas = "^0.10.0"
openpyxl = "^3.1.0"
xlrd = "^2.0.1"
pyodbc= "^4.0.1"
pydantic = "^1.10.0"
setuptools = "<60.0.0"
pygeos = "^0.14"
typing-extensions = "4.7.1"
click = "^8.1.7"
fiona = ">=1.8,<1.10"

[tool.poetry.group.dev.dependencies]
ipykernel = ">=6.0.0"
black = ">=23.0.0"
isort = ">=5.0.0"
pytest = ">=7.0.0"
pyright = "^1.1.359"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.setuptools.package_data]
veg2hab = ["veg2hab/package_data/*"]

[tool.black]
line-length = 88

[tool.isort]
profile = "black"
