[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "hkkang_utils"
version = "0.2.38"
authors = [{name="Hyukkyu Kang", email="hyukkyukang@gmail.com"}]
description = "A collection of useful util functions"
readme = "README.md"
requires-python = ">=3.6"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

dependencies=[
    "python-dotenv",
    "nltk",
    "numpy",
    "omegaconf",
    "pglast",
    "psycopg[binary,pool]",
    "slack_sdk",
    "torch",
    "ujson",
    "wandb",
    "dacite"
]

[project.urls]
"Homepage" = "https://github.com/hyukkyukang/python_utils"
"Bug Tracker" = "https://github.com/hyukkyukang/python_utils/issues"
