[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "codepub"
version = "1.6"
authors = [
  { name="Vasilisa Kovaleva", email="vasilisa.kovaliova@gmail.com" },
  { name="Guanchen He", email="hgc01@buaa.edu.cn" },
]
description = "CodePUB"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: BSD License",
    "Operating System :: OS Independent",
]
dependencies = [
    "numpy>=1.23.5,<2.0.0",
    "cvxpy >= 1.3.2"
]

[project.urls]
"Homepage" = "https://codepub.readthedocs.io/en/latest/index.html"
"Bug Tracker" = "https://github.com/meyer-lab-cshl/codepub/issues"
