[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "RediCMS"
version = "0.2.0"
description = ""
readme = "README.md"
authors = [
    { name = "Anvish Inc.", email = "anvish@anvish.in" }
]
license = { text = "CC-BY-NC-ND-4.0" }
keywords = []
classifiers = [
    "Development Status :: 3 - Alpha",
    "Framework :: Django",
    "Programming Language :: Python :: 3.12",
    "License :: Other/Proprietary License"
]
dependencies = [
    "django>=5.1.3",
    "djangorestframework>=3.15.2"
]
requires-python = ">=3.12"

#[project.urls]
#Homepage = "https://github.com/yourusername/redicms"
