[project]
name = "eznbtemplater"
version = "0.1.2"
description = "Generate PDF and Jupyter Notebook files from a Notebook template"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "nbconvert>=7.16.4",
    "nbformat>=5.10.4",
]

packages = [
    { include = "eznbtemplater" },
]
include = ["eznbtemplater/templates/*"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv]
dev-dependencies = [
    "black>=24.10.0",
    "eznbtemplater",
    "pandas-stubs>=2.2.3.241009",
    "pandas>=2.2.3",
    "pre-commit>=4.0.1",
    "pytest>=8.3.3",
    "tabulate>=0.9.0",
    "twine>=5.1.1",
]
package = true

[tool.uv.sources]
eznbtemplater = { workspace = true }
