[tool.poetry]
name = "ClockParts"
version = "0.1.46"
description = "Dynamic task scheduler"
authors = ["Emerson Silva"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"
colorama = "^0.4.6"
psutil = "^6.1.0"


[[tool.poetry.source]]
name = "foo"
url = "https://pypi.example.org/simple/"
priority = "supplemental"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
