#:schema https://json.schemastore.org/pyproject.json
[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]

[dependency-groups]
dev = ["icecream>=2.1.3", "jinja2>=3.1.4", "marimo>=0.9.17"]
docs = [
  "mdx-truly-sane-lists>=1.3",
  "mkdocs-gen-files>=0.5.0",
  "mkdocs-git-committers-plugin-2>=2.4.1",
  "mkdocs-git-revision-date-localized-plugin>=1.3.0",
  "mkdocs-literate-nav>=0.6.1",
  "mkdocs-material[imaging]>=9.5.44",
  "mkdocs-section-index>=0.3.9",
  "mkdocs>=1.6.1",
  "mkdocstrings-python>=1.12.2",
  "mkdocstrings>=0.27.0",
  "pymdown-extensions>=10.12",
]

[project]
authors = [
  { email = "30631553+liblaf@users.noreply.github.com", name = "liblaf" },
]
dependencies = [
  "gitpython>=3.1.43",
  "jaxtyping>=0.2.34",
  "lazy-loader>=0.4",
  "loguru>=0.7.2",
  "pydantic-settings>=2.6.1",
  "pydantic>=2.9.2",
  "rich>=13.9.4",
  "ruamel-yaml>=0.18.6",
  "tomlkit>=0.13.2",
  "tqdm>=4.66.5",
  "ubelt>=1.3.6",
]
description = "Add your description here"
name = "liblaf-toolkit"
readme = "README.md"
requires-python = ">=3.11"
version = "0.0.9"

[project.optional-dependencies]
comet = ["comet-ml>=3.47.2"]
jax = ["jax>=0.4.35"]
numpy = ["numpy>=2.1.3"]
torch = ["torch>=2.5.1"]

[project.urls]
"Changelog" = "https://github.com/liblaf/python-toolkit/blob/main/CHANGELOG.md"
"Homepage" = "https://github.com/liblaf/python-toolkit"
"Issue Tracker" = "https://github.com/liblaf/python-toolkit/issues"
"Release Notes" = "https://github.com/liblaf/python-toolkit/releases"
"Source Code" = "https://github.com/liblaf/python-toolkit"

[tool.hatch.build.targets.wheel]
packages = ["src/toolkit"]

[tool.hatch.metadata]
allow-direct-references = true

[tool.uv]
default-groups = ["dev", "docs"]
managed = true
package = true
