# contents of pyproject.toml
[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "epitope_aligner"
version = "0.1.1"
authors = [{ name = "David Wells", email = "david.wells@barinthusbio.com" }]
description = "Easily map epitope coordinates between sequences in an alignment"
readme = { file = "README.md", content-type = "text/markdown" }

requires-python = ">=3.10"

dependencies = [
  "pandas",
  "biopython",
  "scipy",
  "matplotlib"
]