[project]
name = "volkoff"
version = "0.1.3"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "base58>=2.1.1",
    "cryptography>=43.0.3",
    "ecdsa>=0.19.0",
    "keyboard>=0.13.5",
    "pytest>=8.3.3",
    "questionary>=1.10.0",
    "rich>=13.9.4",
]

[tool.uv]
dev-dependencies = [
    "aider-chat>=0.63.2",
    "ruff>=0.7.4",
]

[project.scripts]
vk = "volkoff.main:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
