[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "loone_data_prep"
version = "0.1.8"
description = "Prepare data to run the LOONE model."
readme = "README.md"
license = { file = "LICENSE" }
authors = [{ name = "Osama Tarabih", email = "osamatarabih@usf.edu" }]
maintainers = [
    { name = "Michael Souffront", email = "msouffront@aquaveo.com" },
    { name = "James Dolinar", email = "jdolinar@aquaveo.com" },
]
dependencies = [
    "rpy2",
    "retry",
    "numpy<2",
    "pandas",
    "scipy",
    "geoglows==0.27.1",
]
