[project]
name = "llvmcovdiff"
version = "0.0.3"
authors = [
  { name="wjk", email="warrenwjk@qq.com" },
]
description = "Compare two llvm-cov html coverage report."
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = ["beautifulsoup4"]

[project.urls]
Homepage = "https://github.com/am009/llvm-cov-html-diff"
Issues = "https://github.com/am009/llvm-cov-html-diff/issues"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
