[project]
name = "grelmicro"
version = "0.1.0"
description = "Grelmicro is a tool-kit designed to streamline the development cloud-native applications with FastAPI."
license = "MIT"
authors = [{ name = "LoÃ¯c Gremaud", email = "grelinfo@gmail.com"}]
readme = "README.md"

classifiers = [
    "Intended Audience :: Information Technology",
    "Intended Audience :: System Administrators",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python",
    "Topic :: Internet",
    "Topic :: Software Development :: Libraries :: Application Frameworks",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: Software Development :: Libraries",
    "Topic :: Software Development",
    "Typing :: Typed",
    "Development Status :: 1 - Planning",
    "Environment :: Web Environment",
    "Framework :: AsyncIO",
    "Framework :: FastAPI",
    "Framework :: Pydantic",
    "Framework :: Pydantic :: 2",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
]


requires-python = ">=3.11"
dependencies = [
    "anyio>=4.0.0",
    "pydantic>=2.0.0",
    "fast-depends>=2.0.0"
]

[project.optional-dependencies]
postgres = [
    "asyncpg>=0.30.0",
]
redis = [
    "redis>=5.0.0",
]
cli = [
    "typer>=0.12.3",
]

[dependency-groups]
dev = [
    "pytest-cov>=6.0.0",
    "pytest>=8.0.0",
    "mypy>=1.12.0",
    "ruff>=0.7.4",
    "testcontainers[postgres,redis]>=4.8.0",
    "pytest-timeout>=2.3.1",
    "pytest-mock>=3.14.0",
    "pytest-randomly>=3.16.0",
    "pre-commit>=4.0.1",
    "fastapi>=0.115.5",
    "fastapi-cli>=0.0.5",
]


[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"


[tool.ruff]
target-version = "py311"

[tool.ruff.lint]
select = ["ALL"]
ignore = ["COM812", "ISC001"] # Ignore rules conflicting with the formatter.

[tool.ruff.lint.extend-per-file-ignores]
"examples/*" = [
    "ANN", # flake8-annotations
    "ARG", # flake8-unused-arguments
    "D",   # pydocstyle
    "INP", # flake8-no-pep420
]
"tests/*" = [
    "S101",   # assert
]

[tool.ruff.lint.pycodestyle]
max-line-length = 100 # reports only line that exceed 100 characters.

[tool.ruff.lint.pydocstyle]
convention = "pep257"

[tool.ruff.lint.pylint]
max-args = 10

[tool.mypy]
scripts_are_modules = true
plugins = [
  "pydantic.mypy"
]
follow_imports = "silent"
warn_redundant_casts = true
warn_unused_ignores = true
disallow_any_generics = true
check_untyped_defs = true
no_implicit_reexport = true
disallow_untyped_defs = true

[[tool.mypy.overrides]]
module = ["asyncpg", "testcontainers.*"]
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = ["single_file_app"]
disallow_untyped_defs = false


[tool.pytest.ini_options]
addopts = """
    --cov=grelmicro
    --cov-fail-under=100
    --cov-report term:skip-covered
    --cov-report xml:coverage.xml
    --strict-config
    --strict-markers
"""

testpaths = "tests"

[tool.coverage.report]
sort = "-Cover"
exclude_also = [
    "if TYPE_CHECKING:",
    "class .*\\bProtocol\\):",
]
