[project]
name = "nonebot-adapter-mail"
version = "1.0.0-alpha.1"
description = "Mail adapter for nonebot2"
authors = [
    { name = "mobyw", email = "mobyw66@gmail.com" },
]
dependencies = [
    "nonebot2~=2.3.3",
    "aiosmtplib~=3.0.2",
    "aioimaplib~=1.0.1",
    "pydantic[email]>=1.10.0,<3.0.0,!=2.5.0,!=2.5.1",
    "mail-parser~=4.0.0",
]
requires-python = "<4.0,>=3.9"
readme = "README.md"

[project.license]
text = "MIT"

[tool.black]
line-length = 88
target-version = [
    "py39",
    "py310",
    "py311",
    "py312",
]
include = "\\.pyi?$"
extend-exclude = ""

[tool.isort]
profile = "black"
line_length = 88
length_sort = true
skip_gitignore = true
force_sort_within_sections = true
src_paths = [
    "nonebot",
    "tests",
]
extra_standard_library = [
    "typing_extensions",
]

[tool.ruff]
line-length = 88
target-version = "py39"

[tool.ruff.lint]
select = [
    "F",
    "W",
    "E",
    "UP",
    "ASYNC",
    "C4",
    "T10",
    "T20",
    "PYI",
    "PT",
    "Q",
    "RUF",
]
ignore = [
    "E402",
    "UP037",
    "RUF001",
    "RUF002",
    "RUF003",
]

[tool.ruff.lint.flake8-pytest-style]
fixture-parentheses = false
mark-parentheses = false

[tool.pyright]
pythonVersion = "3.9"
pythonPlatform = "All"
typeCheckingMode = "standard"
reportShadowedImports = false
disableBytesTypePromotions = true

[tool.pyright.defineConstant]
PYDANTIC_V2 = true

[[tool.pyright.executionEnvironments]]
root = "./tests"
extraPaths = [
    "./",
]

[[tool.pyright.executionEnvironments]]
root = "./"

[tool.pdm]
distribution = true

[tool.pdm.dev-dependencies]
dev = [
    "ruff>=0.7.0",
    "isort>=5.13.2",
    "black>=24.0.0",
    "nonemoji>=0.1.4",
    "pre-commit>=4.0.1",
]

[tool.pdm.build]
includes = [
    "nonebot",
]

[build-system]
requires = [
    "pdm-backend",
]
build-backend = "pdm.backend"
