[builld-system]
requires = ["hatchling"]
build-backend = "hatchling.build"


[project]
name = "fedj-webfinger"
version = "0.0.2"
readme = "README.md"

dependencies = [
    "django>=4"
]

[project.urls]
Homepage = "https://github.com/jakekara/fedjangiverse/"
Issues = "https://github.com/jakekara/fedjangiverse/issues"
