[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "pgdbpool"
version = "0.97rc1"
authors = [
  { name="Claus PrÃ¼fer", email="pruefer@webcodex.de" },
]
description = "A tiny database de-multiplexer primarily scoped for Web- / Application Server."
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
    "Operating System :: OS Independent",
]
dependencies = [
	"psycopg2"
]

[project.urls]
Homepage = "https://github.com/clauspruefer/python-db-pool"
Issues = "https://github.com/clauspruefer/python-db-pool/issues"
