[tool.poetry]
name = "meteocat"
version = "0.1.4"
description = "Script para obtener datos meteorológicos de la API de Meteocat"
authors = ["figorr <jdcuartero@yahoo.es>"]
license = "Apache-2.0"
readme = "README.md"
repository = "https://gitlab.com/figorr/meteocat"
keywords = ['meteocat']
include = ["LICENSE"]


[tool.poetry.dependencies]
python = "3.12.7"
requests = "^2.32.3"
python-dotenv = "^1.0.1"
simplejson = "^3.19.3"
setuptools = "^75.5.0"
python-semantic-release = "^9.14.0"
twine = "^5.1.1"


[tool.semantic_release]
branch = "master"  # Define la rama desde la que se harán los lanzamientos
version_source = "commit"  # Determina la versión basada en los commits
version_variable = "meteocat/__init__.py:__version__"  # Ubicación de la variable de versión
changelog = { file = "CHANGELOG.md" }  # Genera el changelog en el archivo especificado
upload_to_pypi = true  # Sube automáticamente la versión a PyPI


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
