[tool.poetry]
name = "openfund-plugin-up"
version = "0.0.2"
description = "Openfund plugin that updates dependencies and bumps their versions in pyproject.toml file"
authors = ["yang99love"]
packages = [
    { include = "openfund_plugin_up", from = "src" },
]
license = "MIT"
readme = "README.md"
keywords=[
    "packaging",
    "dependency",
    "openfund",
    "update",
    "upgrade",
]
classifiers=[
    "Development Status :: 5 - Production/Stable",
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[tool.poetry.dependencies]
python = "^3.8"
openfund = "^0.1.6"

[tool.poetry.group.dev.dependencies]
pre-commit = "^2.21.0"
pytest = "^7.4.4"
pytest-mock = "^3.14.0"

# group = "openfund.application.plugin"
[tool.poetry.plugins."openfund.application.plugin"]
up = "openfund_plugin_up.plugin:UpApplicationPlugin"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 80

[tool.isort]
profile = "black"
