[tool.poetry]
name = "eqr"
version = "0.1.1"
description = "A python package to perform quantile regression with more meaningful epistemic uncertainty estimates through training set augmentation using synthetic data. A blend of discriminative and generative models."
authors = ["Sebastian Khan <sebastiank17@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
keras = "^3.6.0"
jax = "^0.4.35"
numpy = "^2.1.3"
scikit-learn = "^1.5.2"
matplotlib = "^3.9.2"
scienceplots = "^2.1.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
